const ACTIONS = {
  LOGIN: "LOGIN",
  MESSAGEUSER: "MESSAGEUSER",
  GET_TOKEN: "GET_TOKEN",
  GET_USER: "GET_USER",
  GET_ALL_USER: "GET_ALL_USER",
  GET_CURRENT_CHAT: "GET_CURRENT_CHAT",
  CREATE_CVS_CHAT: "CREATE_CVS_CHAT",
  CHECK_CVS_CHAT_FALSE: "CHECK_CVS_CHAT_FALSE",
  CHECK_CVS_CHAT_SUCCESS: "CHECK_CVS_CHAT_SUCCESS",
  VIDEO_CALL_BTN_BLOCK: "VIDEO_CALL_BTN_BLOCK",
  VIDEO_CALL_BTN_NONE: "VIDEO_CALL_BTN_NONE",
  VIDEO_CALL_SUCCESS: "VIDEO_CALL_SUCCESS",
  VIDEO_CALL_FAILS: "VIDEO_CALL_FAILS",
  VIDEO_CALL_REQUEST: "VIDEO_CALL_REQUEST"
};


export default ACTIONS;
